georust/gdal

- src/lib.rs
- src/vector/dataset.rs
- src/vector/defn.rs
- src/vector/driver.rs
- src/vector/feature.rs
- src/vector/geometry.rs
- src/vector/layer.rs
- src/vector/mod.rs
- src/vector/ogr.rs
- src/vector/tests/mod.rs
Here's basic support for creating a new dataset and writing features. Just the geometries, no properties yet.
> Write geometries to new dataset

- examples/metadata.rs
- src/gdal_major_object.rs
- src/lib.rs
- src/metadata.rs
- src/raster/dataset.rs
- src/raster/driver.rs
- src/raster/tests.rs
- src/vector/dataset.rs
- src/vector/layer.rs
This is a first step to introduce metadata access: #20.
TODO: RasterBand metadata. This probably needs a `struct RasterBand`.
> first version of metadata handling

- Cargo.toml
- src/lib.rs
- src/vector/gdal_to_geo.rs
- src/vector/geo_to_gdal.rs
- src/vector/tests/convert_geo.rs
This should allow to use rust-gdal with a current version of rust-geo :)
> Adapt to current rust-geo

- gdal-sys/src/ogr.rs
- gdal-sys/src/osr.rs
- src/errors.rs
- src/spatial_ref/srs.rs
- src/spatial_ref/tests.rs
- src/vector/dataset.rs
- src/vector/defn.rs
- src/vector/feature.rs
- src/vector/geometry.rs
- src/vector/layer.rs
- src/vector/mod.rs
- src/vector/tests/mod.rs
Here are some API extensions I needed for my application. I'm working with GDAL 2.1, but it should still work with GDAL >= 1.11. Two tests are failing with 2.1 though.
> API extensions

- .gitignore
- gdal-sys/build.rs
- gdal-sys/src/ogr.rs
- src/spatial_ref/srs.rs
- src/vector/geometry.rs
My first official foray into FFI with Rust, so I may have missed some stuff.
FWIW, I wrote the Ruby gem [ffi-gdal](https://bitbucket.org/agrian/ffi-gdal) (which may or may not be well done, but either way, I've spent hours with the stuff)--I dunno if that could serve as an aid in wrapping some of stuff that's not yet done, but I thought I'd post just in case it helps in some way.
> Add a few area-related wrappers

- examples/read_write_ogr.rs
- examples/spatial_reference.rs
- examples/write_ogr.rs
- src/lib.rs
- src/spatial_ref/tests.rs
- src/vector/tests/mod.rs
This includes #52 and might need to be rebased (although I don't think so).
> Fix tests on GDAL 2.2 and some warnings

- Cargo.toml
- src/lib.rs
- src/vector/gdal_to_geo.rs
- src/vector/geo_to_gdal.rs
- src/vector/tests/convert_geo.rs
> Migrate to the geo-types crate

- Cargo.toml
- examples/read_write_ogr.rs
- examples/read_write_ogr_datetime.rs
- examples/spatial_reference.rs
- examples/write_ogr.rs
- src/dataset.rs
- src/driver.rs
- src/errors.rs
- src/metadata.rs
- src/raster/rasterband.rs
- src/raster/tests.rs
- src/raster/warp.rs
- src/spatial_ref/srs.rs
- src/spatial_ref/tests.rs
- src/utils.rs
- src/vector/defn.rs
- src/vector/feature.rs
- src/vector/geo_to_gdal.rs
- src/vector/geometry.rs
- src/vector/layer.rs
- src/vector/tests/mod.rs
> replace failure with thiserror

- Cargo.toml
- src/vector/geo_to_gdal.rs
Successor of #106.
Still no idea if this is desirable, but I needed it so I might as well send this PR. Feel free to close if it's too compatibility-breaking.
> Update geo-types from 0.4 to 0.6.1

- src/vector/layer.rs
- src/vector/tests/mod.rs
> Replace force flag by get_extent and try_get_extent

- CHANGES.md
- src/dataset.rs
---
Fixes https://github.com/georust/gdal/pull/164#issuecomment-783607743
> Avoid calling GDALAllRegister twice

- CHANGES.md
- src/vector/layer.rs
- src/vector/mod.rs
- src/vector/vector_tests/mod.rs
---
Alternative implementation of https://github.com/georust/gdal/pull/160 using `enum`.
> Implement wrapper for OGR_L_TestCapability - enum implementation

- src/vector/feature.rs
> Fix typo in method name

- CHANGES.md
> Add #175 to changelog

- gdal-sys/src/lib.rs
- src/spatial_ref/tests.rs
- src/vector/geometry.rs
- src/vector/layer.rs
- src/vector/sql.rs
- src/vector/vector_tests/mod.rs
> allow clippy::upper_case_acronyms where needed

- CHANGES.md
- src/vector/geometry.rs
> Add Geometry::from_wkb and Geometry::wkb methods

- CHANGES.md
- src/vector/geometry.rs
> Add wrapper for `OGR_G_Buffer`

- CHANGES.md
- src/errors.rs
- src/vector/gdal_to_geo.rs
- src/vector/vector_tests/convert_geo.rs
---
These are the in #196 proposed in changes. See that issue for more on the reasoning for this.
> Use TryFrom to convert to geo-types

- Readme.md
> Update Readme.md: remove spurious brackets from ci badge

- CHANGES.md
- Cargo.toml
- [x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
> Bump edition to 2021 & update changelog to release 0.12

- src/vector/feature.rs
> Derive Clone for FieldValue

- src/dataset.rs
> Expanded documentation for `GeoTransform`

- script/doctest-output.sh
- src/raster/rasterband.rs
- src/version.rs
---
Minor refinements to rasterband docs.
> Rasterband documentation refinements.

- gdal-sys/build.rs
- src/programs/raster/mdimtranslate.rs
- src/raster/mdarray.rs
- src/raster/tests.rs
- src/vector/vector_tests/mod.rs
> Fix some clippy warnings

- .cargo/config.toml
- src/dataset.rs
- src/driver.rs
- src/lib.rs
- src/raster/rasterband.rs
- src/vector/mod.rs
---
This helps us ensure the documentation abides by deprecations.
> Disallow warnings in doctests

- Cargo.toml
- src/vector/gdal_to_geo.rs
- src/vector/vector_tests/convert_geo.rs
> Fix deprecations introduced in geo-types v0.7.8.

- CHANGES.md
- Cargo.toml
> Disable default chrono features

- src/vsi.rs
> Remove test failing on GDAL 3.6

- examples/read_write_ogr_datetime.rs
- gdal-sys/build.rs
- src/config.rs
- src/raster/rasterband.rs
- src/test_utils.rs
- src/vector/feature.rs
- src/vector/geometry.rs
> Fix clippy warning

- README.md
> Bump GDAL version in README

- CHANGES.md
- Cargo.toml
- build.rs
- examples/metadata.rs
- examples/spatial_reference.rs
- examples/write_ogr.rs
- gdal-sys/Cargo.toml
- gdal-sys/build.rs
- src/cpl.rs
- src/dataset.rs
- src/raster/types.rs
- src/spatial_ref/srs.rs
- src/vector/geo_to_gdal.rs
- src/vector/geometry.rs
> Make clippy happy

- CHANGES.md
- src/vector/ops/conversions/formats.rs
> Add Geometry::from_geojson

- CHANGES.md
- src/vector/ops/conversions/formats.rs
> Add `Geometry::from_gml`

- .github/workflows/ci.yml
> Use latest minor releases and fix Arrow GPG errors

- CHANGES.md
- bors.toml
- src/lib.rs
> Expose Gcp and GcpRef

- src/vector/feature.rs
- src/vector/layer.rs
> Fix clippy warnings

- CHANGES.md
- src/vector/geometry.rs
> Implement `Geometry::flatten_to_2d`

- .github/workflows/ci.yml
- bors.toml
> Run CI on GDAL 3.7.3

- src/version.rs
> version.rs test: make it work with a GDAL debug build

- gdal-sys/Readme.md
> gdal-sys/Readme.md: add hint about setting GDAL_VERSION

- CHANGES.md
- src/raster/types.rs
- src/spatial_ref/mod.rs
- src/spatial_ref/srs.rs
- src/spatial_ref/transform.rs
- src/vector/layer.rs
> Created `enum AxisMappingStrategy` for `OSRAxisMappingStrategy` ordinals.

- CHANGES.md
- src/vector/feature.rs
- src/vector/layer.rs
> Change `Feature::set_field_xxx` to take `&mut self`

- src/raster/rasterize.rs
> Fixes new clippy lint `items-after-test-module`

- src/raster/types.rs
> Added missing variant in `GdalDataType::iter`.

- CHANGES.md
- src/raster/rasterband.rs
- src/raster/tests.rs
> Add Dataset::rasterbands

- .github/workflows/ci.yml
> Bump CI GDAL to 3.8.5

- .github/workflows/ci.yml
- tests/error_handler.rs
> Test GDAL 3.9.1 on CI

- Cargo.toml
- README.md
- gdal-sys/Cargo.toml
- src/lib.rs
> Prepare for 0.17 release

- CHANGES.md
> Add 0.17 to changelog

- CHANGES.md
- src/vector/defn.rs
- src/vector/layer.rs
> Add Layer::defn::geometry_type()

- .github/workflows/ci.yml
> Install `sqlite3` on Linux and enable `driver_sqlite`

- .github/workflows/ci.yml
> Test Ubuntu 22.04 on CI

- gdal-src/Cargo.toml
> Include more files into gdal-src

- src/cpl.rs
- src/gcp.rs
- src/metadata.rs
- src/raster/rasterband.rs
- src/vector/feature.rs
- src/vector/layer.rs
- src/vector/options.rs
- src/vector/sql.rs
- src/vector/transaction.rs
- src/vsi.rs
> Fix Clippy `needless_lifetimes`

- CHANGES.md
- src/vector/mod.rs
> Make `GeometryRef` public

- .github/workflows/ci.yml
> Use GDAL 3.10.1 on CI

- gdal-src/Cargo.toml
---
It won't be used before a new proj release with https://github.com/georust/proj/pull/218 is issued but it shouldn't cause build errors
> Update libsqlite3-sys to allow 0.31 as well

- CHANGES.md
- src/spatial_ref/transform.rs
- src/vector/feature.rs
- src/vector/layer.rs
- src/vector/ops/transformations.rs
> Reset layer when droppping feature iterator

- .github/workflows/ci.yml
> Bump GDAL to 3.10.2

- gdal-src/Cargo.toml
> Bump libsqlite3-sys to support version 0.32 as well

- Cargo.lock
- Cargo.toml
- gdal-src/Cargo.toml
- gdal-sys/Cargo.toml
> bump sys and src versions

- Cargo.lock
- gdal-src/Cargo.toml
- gdal-sys/build.rs
> Bump libsqlite3-sys and proj-sys dependencies

- .github/workflows/ci.yml
- README.md
- examples/read_write_ogr.rs
- examples/read_write_ogr_datetime.rs
- src/lib.rs
> Fix a couple of typos

- CHANGES.md
- src/dataset.rs
- src/errors.rs
- src/lib.rs
- src/options.rs
- src/raster/tests.rs
- src/thread_safe.rs
> Add `Dataset::try_into_thread_safe`
