examples/metadata.rs, examples/rasterband.rs, src/gdal_major_object.rs, src/metadata.rs, src/raster/dataset.rs, src/raster/driver.rs, src/raster/gdal.rs, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs, src/vector/dataset.rs, src/vector/layer.rs
This adds a `struct RasterBand` and moves all related functions from `Dataset` to `RasterBand`.
I'm not sure if the read/write functions in Dataset should be removed or stay as shortcuts. As requesting a `RasterBand` from a `Dataset` should return an `Option<RasterBand>` i adapted the shortcuts to reflect this... 
Additionally i added some more Rasterband specific functions and implemented Metadata #20 for RasterBand.
=> Add RasterBand

Cargo.toml, examples/rasterband.rs, gdal-sys/src/cpl_error.rs, gdal-sys/src/gdal.rs, gdal-sys/src/lib.rs, gdal-sys/src/ogr.rs, gdal-sys/src/ogr_enums.rs, src/errors.rs, src/lib.rs, src/metadata.rs, src/raster/dataset.rs, src/raster/driver.rs, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs, src/raster/warp.rs, src/utils.rs, src/vector/dataset.rs, src/vector/driver.rs, src/vector/feature.rs, src/vector/geo_to_gdal.rs, src/vector/geometry.rs, src/vector/layer.rs, src/vector/mod.rs, src/vector/tests/convert_geo.rs, src/vector/tests/mod.rs
I started replacing Option (and panics) with Result #28 . Everything should work but the `ToGdal` trait needs some attention:
```
pub trait ToGdal {
fn to_gdal(&self) -> Geometry;
}
```
Since the creation of a new `Geometry` can fail in GDAL there are now many unused Results in the `geo_to_gdal` module. Instead of using `unwrap()` i would suggest to change the trait to return a `Result`:
```
pub trait ToGdal {
fn to_gdal(&self) -> Result<Geometry>;
}
```
=> Replace Option with Result

examples/spatial_reference.rs, gdal-sys/src/lib.rs, gdal-sys/src/ogr.rs, gdal-sys/src/osr.rs, src/lib.rs, src/spatial_ref/mod.rs, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs, src/vector/geometry.rs
Hi!
Thanks for providing an access to GDAL/OGR api in rust!
I was interested to transform ogr geometries to an other SRS so I wrapped some functions of the [OGR spatial reference](http://www.gdal.org/ogr__srs__api_8h.html) part of the gdal api (in order to be able to use *OGRSpatialReferenceH* and *OGRCoordinateTransformationH* types from C in rust).
It only uses a few major functions, as my main objective was simply to do something like :
```rust
let spatial_ref1 = SpatialRef::new_from_epsg(4326);
let spatial_ref2 = SpatialRef::new_from_epsg(3035);
let htransform = CoordTransform::new(&spatial_ref2, &spatial_ref1);
// an ogr Geometry :
geometry.transform(&htransform);
// or :
// geometry.transform_to(&spatial_ref1)
```
Could you be interested to merge these changes ? It also includes a …
=> Allow to transform ogr geometries to other SRS

src/errors.rs, src/metadata.rs, src/raster/dataset.rs, src/raster/driver.rs, src/spatial_ref/srs.rs, src/utils.rs, src/vector/dataset.rs, src/vector/driver.rs, src/vector/feature.rs, src/vector/geometry.rs, src/vector/layer.rs
This removes most `.unwrap()` calls from library methods and updates dependency versions.
Additionally `ErrorKind::NullPointer` now tries to get a GDAL error msg.
=> remove unwraps and add more error msgs.

src/vector/geometry.rs
This fixes #45. All tests now reliably complete without a segfault.
=> Change Geometry::set_spatial_reference so it only borrows srs (fixes issue #45)

gdal-sys/src/osr.rs, src/spatial_ref/srs.rs, src/vector/geometry.rs
This reverts the previous fix and changes the impl of Drop for SpatialRef
to use OSGRelease instead of OSRDestroySpatialReference. This will just
decrement the reference count for the SpatialRef and destroy it if the
count reaches 0.
This resolves a valgrind error that was still being reported after the previous
fix. This fix also has the advantage that it does not change the API for
existing users.
=> A better fix for issue #45

gdal-sys/src/lib.rs, gdal-sys/src/ogr.rs, gdal-sys/src/ogr_structs.rs, src/vector/layer.rs, src/vector/tests/mod.rs
I'm not sure whether it's all right to expose `OGREnvelope` directly, any preferences?
=> Wrap OGR_L_GetExtent

src/raster/rasterband.rs, src/raster/tests.rs
Currently you can retrieve a no data value for a raster, but there doesn't exist a method to set it. Thought this might be useful for someone else other than myself.
=> Add method to set no data values for raster bands

src/raster/mod.rs
This makes the `GdalType` trait public, allowing user code to use it as a type bound. It resolves #48.
I'm a bit new to Rust, so if this is not the right tack please let me know!
cc @jdroenner
=> Make GdalType trait public

src/vector/geometry.rs, src/vector/mod.rs, src/vector/ops/geometry/intersection.rs, src/vector/ops/geometry/mod.rs, src/vector/ops/mod.rs
I built off of #75 since it is already approved. 
gdal-sys has vector methods for both layers and geometries. It would be nice if these operations could use one trait, but unfortunately the intersection function signature for layers and geometries is much different.
Seeking comments on the location for these traits. I went with `crate::vector::ops::geometry::intersection`.
=> Define Geometry Intersection trait and implement it for Geometry

src/vector/feature.rs
=> Add support for Integer64

Cargo.toml, build.rs, gdal-sys/Cargo.toml, gdal-sys/build.rs, src/raster/rasterband.rs, src/raster/tests.rs, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs, src/vector/tests/mod.rs
This PR changes the build.rs file for gdal-sys and introduces a build.rs for gdal. It makes conditional compilation for version handling more convenient. However, it is still not very pretty.
In gdal-sys, the lib version is now used to select the correct binding file. On Linux it is provided by pkg-config if the gdal lib is detected.
In gdal, the features for versions are removed. The actual GDAL version is requested from gdal-sys and the config parameters are generated.
The changes for **gdal-sys** are:
- version specification as environmental variable  or auto-detection using pkg-config. (i guess windows will require the `GDAL_VERSION` variable to be set).
- no more features to select versions
The changes for **gdal** are: 
- Features for versions are removed. 
- The Current GDAL …
=> Detect GDAL version at build time / remove version features

src/raster/rasterband.rs, src/raster/tests.rs
+ add `read_into_slice`
+ make `read_as` and `read_as_array` to use it
+ minor doc fixes
+ add test for `read_into_slice`
closes #82
=> Ability to read into preallocated slice for rasterband

src/vector/layer.rs, src/vector/tests/mod.rs
Nice for progress bars and just generally good to have proper size_hints if cheap to compute.
=> Add feature_count{,_force} and implement Iterator::size_hint

src/metadata.rs, src/raster/tests.rs
Allows listing all domains for the specified Metadata and retrieving the strings for a given domain.
=> added additional metadata retrieval options.

src/vector/geometry.rs, src/vector/layer.rs, src/vector/tests/mod.rs
There was some inconsistency in function naming:
- Geometry::spatial_reference
- Layer::spatial_reference
- GeomField::spatial_ref
I chose spatial_ref, rather than spatial_reference, as the canonical
form because:
- abbreviations are common in Rust
- "ref" for "reference" is already well-known to Rust devs, e.g. RefCell
- the returned type is called SpatialRef
- the GDAL API also consistently uses SpatialRef
=> Rename spatial_reference to spatial_ref

src/spatial_ref/srs.rs
c_char is not set to i8 on every architecture, and indeed, this fixes
the build on arm64 and possibly other architectures as well.
Closes #122.
=> Fix i8 ptr instead of c_char ptr passed to OSRImportFromESRI()

gdal-sys/build.rs
The gdal-sys docs are currently failing to build:
https://docs.rs/crate/gdal-sys/0.3.0/builds/326757
I think this is because the build script requires libgdal to actually be installed. This adds a short circuit to skip the normal build process and hardcodes a version of the prebuilt bindings to use when generating docs.
=> fix docs.rs build for gdal-sys (hopefully)

Readme.md
It seems like maybe previously someone was manually producing and publishing the docs to gh-pages, and it's gotten out of date. 
It might be easier for you to just point to docs.rs which automatically builds your docs whenever you publish.
=> update docs link to point at docs.rs

gdal-sys/build.rs
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
Fixes #137
If pkg-config is not installed on your system you should see error output like this:
```
$ cargo build                                                 
Compiling gdal-sys v0.3.1 (/Users/mkirk/src/georust/gdal/gdal-sys)
error: failed to run custom build command for `gdal-sys v0.3.1 (/Users/mkirk/src/georust/gdal/gdal-sys)`
Caused by:
process didn't exit successfully: `/Users/mkirk/src/georust/gdal/target/debug/build/gdal-sys-e669765d1e341154/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=GDAL_STATIC
cargo:rerun-if-env-changed=GDAL_DYNAMIC
cargo:rerun-if-env-changed=GDAL_INCLUDE_DIR
cargo:rerun-if-env-changed=GDAL_LIB_DIR …
```
=> better error when pkg-config is not installed.

CHANGES.md, Cargo.toml, src/vector/geo_to_gdal.rs
---
geo-types <T> must now support Debug. Rather than change all the `num_traits:Float` to `num_traits::Float + Debug`, I've leveraged the new `geo_types::CoordFloat` to the same effect. Consequently, we no longer need to explicitly depend on num_traits.
=> update to geo-types 0.7

CHANGES.md, examples/read_write_ogr.rs, examples/read_write_ogr_datetime.rs, examples/write_ogr.rs, fixtures/null_feature_fields.geojson, src/lib.rs, src/vector/feature.rs, src/vector/mod.rs, src/vector/vector_tests/mod.rs
Fixes https://github.com/georust/gdal/issues/132
=> Feature::field returns Result<Option<FieldValue>>

CHANGES.md, src/errors.rs, src/spatial_ref/mod.rs, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs
---
This PR add more bridge functions to gdal::spatial_ref::srs::SpatialRef implementation.
Struct added
* AreaOfUse
Type alias
* AxisOrientationType 
Functions added:
* get_name
* get_angular_units
* get_angular_units_name
* get_linear_units
* get_linear_units_name
* is_geographic
* is_derived_geographic
* is_local
* is_projected
* is_compound
* is_geocentric
* is_vertical
* get_axis_orientation
* get_axis_name
* get_axes_count
* get_area_of_use
Added tests.
=> Add more SpatialRef methods

CHANGES.md, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs
---
Nitpicky follow up to #145. Sorry it didn't occur to me during review! 
Idiomatically, rust API's omit the `get_` prefix from "getters". 
https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter
=> conventional rust naming

CHANGES.md, Cargo.toml, src/dataset.rs
---
This is attempt to fix #154 
This is an api breaking change
This PR allow using `GDAL_OF_XXX` extended flags. 
Implement a `DatasetOptions` to pass to `Dataset::open_ex`
```rust
use gdal::{ Dataset, DatasetOptions }
let dataset = Dataset::open_ex(
"roads.geojson",
DatasetOptions { 
open_flags: GdalOpenFlags::GDAL_OF_UPDATE|GdalOpenFlags::GDAL_OF_VECTOR,
..DatasetOptions::default()
}
)
.unwrap();
```
`GDALAccess` values are supported using [`From`] implementation
```rust
Dataset::open_ex(
"roads.geojson",
DatasetOptions {
open_flags: GDALAccess::GA_Update.into(),
..DatasetOptions::default()
},
)
.unwrap();
```
Note that [following this note](https://github.com/georust/gdal/issues/154#issuecomment-770187560)  `GDAL_OF_SHARED` option is removed from the set of allowed option because it …
=> Support extended flags for open_ex

src/lib.rs
---
A small fix for https://github.com/georust/gdal/pull/155: as `dataset` is a private module, `dataset::GdalOpenFlagls` and `dataset::DatasetOptions`  must be exported in order to be used because they are required with `open_ex`.
=> Add missing dataset exports

src/dataset.rs, src/raster/rasterband.rs
Added documentations for `Dataset` and `RasterBand`, and fixed `cfg()` for some of the `open_ex` flags (it wasn't enabled on gdal 3.0 and above).
Open question:  how to refer to GDAL documentations from our docs?  For many functions, the relevant docs are doxygen links (eg. [GDALOpenEx](https://gdal.org/doxygen/gdal_8h.html#a9cb8585d0b3c16726b08e25bcc94274a)) which could break if it is regenerated upstream (and annoying to update).
---
---
=> Add documentation

CHANGES.md, build.rs, examples/read_write_ogr_datetime.rs, src/dataset.rs
=> Add Dataset::build_overviews

CHANGES.md, examples/rasterband.rs, src/raster/rasterband.rs, src/raster/tests.rs
---
This PR changes the functions used to read rasters by adding an extra parameter to select the resampling algorithm used when `buffer_size != window size` (GDAL needs to interpolate the values) (closes #140)
=> Select resampling algo

CHANGES.md, examples/read_write_ogr.rs, examples/read_write_ogr_datetime.rs, examples/write_ogr.rs, src/dataset.rs, src/lib.rs, src/vector/vector_tests/mod.rs
This adds support for driver-specific `name=value` pairs while also
simplifying the API a bit.
Removes `create_layer_blank` because it seems to serve only niche use
cases and can easily be replaced by `create_layer(Default::default())`.
Fixes #185.
---
=> Replace create_layer arguments list by LayerOptions struct

CHANGES.md, src/driver.rs, src/raster/mod.rs, src/raster/tests.rs
---
Please review the additions I made (related to #190 ).
Also, I think there may be a bug in `dataset.metadata_item();` which makes the test ` test_create_with_band_type_with_options() ` fail, since I can see the COMPRESSION field in the image structure metadata when using `gdalinfo`. Or am I missing something?
gdalinfo output:
```bash
Files: /tmp/test.tif
Size is 256, 256
Image Structure Metadata:
COMPRESSION=LZW
INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  256.0)
Upper Right (  256.0,    0.0)
Lower Right (  256.0,  256.0)
Center      (  128.0,  128.0)
Band 1 Block=128x64 Type=Byte, ColorInterp=Gray
```
test error:
```
thread 'raster::tests::test_create_with_band_type_with_options' panicked at 'assertion failed: `(left == right)`
left: …
```
=> Add raster creation options

src/raster/mod.rs
---
As mentioned in #188, ResampleAlg was not included in the public exports of the raster module (my bad!).
This PR should fix that.
=> Add ResampleAlg to raster pub exports (fixes #188)

CHANGES.md, src/vector/feature.rs
=> Add `Feature::c_feature`

CHANGES.md, src/vector/feature.rs, src/vector/vector_tests/mod.rs
---
I added wrapper functions for the `OGR_F_GetFieldAs…` functions.
Regarding my PR, I have two questions:
1. Is the naming scheme correct for my functions? I oriented myself on the `set_field_double` (, etc.) functions.
2. Should I also implement the list and binary function of *get field as …* or is it sufficient to implement some of them?
=> Get field as x

CHANGES.md, src/vector/layer.rs, src/vector/vector_tests/mod.rs
---
I've added two new functions to the OGR layer wrapper that call…
* OGR_L_SetAttributeFilter
* OGR_L_SetSpatialFilterRect
I've also added tests so that we can see that they work.
=> OGR Layer: Set Attribute Filter & Set Spatial Filter as Rectangle

CHANGES.md, src/config.rs
---
I've added wrappers for `CPLSetThreadLocalConfigOption` and `CPLGetThreadLocalConfigOption` the same way they are already there for the global config.
=> Wrappers for `CPLSetThreadLocalConfigOption` and `CPLGetThreadLocalConfigOption`

CHANGES.md, src/errors.rs, src/lib.rs, src/vsi.rs
---
I mapped the methods `VSIFileFromMemBuffer`, `VSIUnlink`, `VSIGetMemFileBuffer`.
Since I haven't found a good place to put them, I created a new `vsi` module in the root.
There are two methods for creation and retrieval that work with owned data, such that either we give the ownership from our Rust object to GDAL's CPP context or vice versa.
Moreover, there are two methods that work with references and they do not hand over ownership. This is more complicated since we don't want to introduce memory leaks. I created a retrieval method that only gets a function so that we do not hand out data but only a computation result from the function. For creation, I introduced a `MemFileRef` struct that handles the lifetime to the referenced data.
It would be nice if someone would check that my …
=> Mapped VSIMemFile methods

.github/workflows/ci.yml, bors.toml
---
I think the elements in `status` need to match all the GH Action job names we require to succeed.
=> Fix bors integration

CHANGES.md, src/vector/layer.rs
---
set_attribute_filter should take &mut self since OGR_L_SetAttributeFilter resets the reading position.
=> set_attribute_filter shouild take &mut self

src/raster/rasterband.rs
---
`read_band_as` and `write` had incorrect argument lists in the documentation.
=> Fix small doc errors in rasterband

CHANGES.md, src/metadata.rs, src/raster/tests.rs
---
This is a really simple change that allows users to set descriptions on major GDAL objects; that's mostly useful for RasterBands. If you prefer I could just make this a method on `RasterBand` only instead of more generally making it part of the `Metadata` trait.
=> Add set description

CHANGES.md, src/dataset.rs, src/driver.rs
---
`libc::c_char` is a `u8` on `ppc64le`. Using the type definition from `libc` fixes it (maybe for other archs too).
=> Update types to fix build on ppc64le

src/spatial_ref/srs.rs, src/spatial_ref/tests.rs
---
Currently `CoordTransform::transform` accepts three `&mut [f64]` slices (for x, y, and z coordinates).  This prevents us from using it for 2D transform (whereas in the C api, we would have passed null ptr for z).  This PR supports that by checking if the z slice is empty, and passes null_ptr instead.
Also, currently we only check if the x and y slices have the same length.  This causes sigsegv when passing incorrect z slice.  We've also added a assertion for that.
Modified one of the existing tests that didn't use the z coordinate to instead pass an empty slice.
=> Support 2D in CoordTransform

CHANGES.md, Cargo.toml, src/config.rs, src/errors.rs
---
I've attached two options for setting up the global GDAL error callback. One is thread-safe and comes with a new dependecy and the other one is not.
The reason for storing the callback in a static variable is that we cannot pass the ownership to GDAL. We can access a generic pointer via the `pUserData` field and cast it to our function type. Therefore, in order not to leak our `FnMut`, we have to store it somehow and drop it later on.
When we decide on which version to use, I can remove the other one and convert the draft to a PR.
=> Creating error callbacks

CHANGES.md, Cargo.toml, src/errors.rs, src/raster/mod.rs, src/raster/rasterize.rs, src/raster/tests.rs
---
This new function `rasters::rasterize` lets you "burn in" a sequence of `vector::Geometry` objects into a raster `Dataset`.
=> feat: add `GDALRasterizeGeometries` wrapper

CHANGES.md, src/dataset.rs, src/driver.rs, src/raster/tests.rs, src/utils.rs, src/vector/vector_tests/mod.rs, src/vsi.rs
---
According to affirmation in https://github.com/georust/gdal/issues/227 I changed all file paths to be implementing `AsRef<Path>`.
This is based on @lnicola's idea and is similar to https://doc.rust-lang.org/std/fs/struct.File.html#method.open.
This introduced generics on the methods but I guess less code-breaking since you can still input `&str`s.
=> Filenames now must allow references to `Path`

tests/compile-tests/01-features-aliasing-errors.stderr
---
it works with current stable beta and nightly on linux
=> adapt try build expected error to new output

CHANGES.md, src/vector/geometry.rs, src/vector/mod.rs
=> Add geometry_type_to_name function

src/dataset.rs, src/vector/feature.rs, src/vector/layer.rs, src/vector/vector_tests/mod.rs
- [xI agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
---
New Lints (https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten) and formatting errors have been recently introduced to rust, producing errors in the CI (See for example: https://github.com/georust/gdal/pull/260 ). 
This PR addresses this issues.
=> Fix clippy and fmt errors

CHANGES.md, src/spatial_ref/srs.rs, src/vector/defn.rs, src/vector/geometry.rs, src/vector/layer.rs
---
See https://github.com/georust/gdal/pull/257#issuecomment-1096074275
=> Mark `SpatialRef::from_c_obj` as unsafe

CHANGES.md, src/raster/tests.rs, src/vector/feature.rs, src/vector/vector_tests/mod.rs
Also reuse field_idx_from_name instead of duplicating it all over the
place.
---
If you think it's worth a changelog entry, I'll be happy to add one right before merge, to save myself some merge conflicts.
=> Implement missing Feature::set_field_*_list funcs

CHANGES.md, src/dataset.rs
=> Deprecate Transaction::dataset{,_mut} in favour of Deref{,Mut}

CHANGES.md, src/errors.rs, src/raster/rasterband.rs, src/raster/rasterize.rs, src/vector/vector_tests/mod.rs, src/vsi.rs
=> remove `PartialEq` from `GdalError`

CHANGES.md, Cargo.toml, build.rs, gdal-sys/build.rs, gdal-sys/src/lib.rs
Use dynamic code-gen to build-around non-availabiltiy of some packages.
---
=> Fix crate build on docs.rs

CHANGES.md, src/vector/feature.rs, src/vector/mod.rs
=> Add gdal::vector::field_type_to_name

CHANGES.md, src/errors.rs, src/raster/mdarray.rs, src/raster/mod.rs, src/raster/rasterband.rs
---
I noticed that there is a segmentation fault when calling read_as_string for the MDArray if it is not of type string.
This is why I check for its datatype first.
Moreover, there are new Clippy lints that I had to consider.
=> prevent SIGSEGV for non-strings on read string method

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
- [ x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ x ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
=> add raster mask methods

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
=> Add `set_scale` and `set_offset` to `Rasterband`

CHANGES.md, src/errors.rs, src/raster/mdarray.rs, src/raster/mod.rs
---
Before https://github.com/georust/gdal/pull/284, `GdalError` was `Send`.
The previous PR changed it unknowingly.
This PR changes #284 so that `GdalError` is `Send` again.
Moreover, it adds a test that ensures that.
=> enforce that `GdalError` is `Send`

CHANGES.md, src/programs/raster/mdimtranslate.rs, src/programs/raster/mod.rs
---
I created a wrapper around `GDALMultiDimTranslate`. I used part of the logic for the wrapper for the VRT program.
=> wrapper for gdalmdimtranslate

CHANGES.md, src/raster/mdarray.rs, src/raster/mod.rs
---
Added the wrapper for the dimension call for md groups.
=> allow reading dimensions from md groups

CHANGES.md, src/raster/mdarray.rs, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs
=> get_statistics for rasterbands and md rasters

src/raster/mdarray.rs
---
We don't support `GEDTC_COMPOUND` anyway because of the `GdalType` bound. ~~This is stricter than it could be, but should be fine as a quick workaround for #290. We should pass in the data type of the buffer, but it wasn't obvious to me how to do that.~~
Fixes #290
=> Require matching data types in MDArray::read_into_slice

CHANGES.md, src/lib.rs, src/programs/raster/mdimtranslate.rs, src/raster/mdarray.rs, src/raster/tests.rs, src/test_utils.rs
=> use tempfiles to not access file multiple times

CHANGES.md, src/raster/mdarray.rs
---
Fixes #298
r? @ChristianBeilschmidt
=> Fix dimensions getter when no dimensions are available

Cargo.toml, src/errors.rs, src/lib.rs, src/raster/mdarray.rs, src/raster/rasterband.rs
---
Followed approach outlined [here](https://gist.github.com/jam1garner/7d909e1d0e5986b9b8d50830314bec63).
Rendering can be tested locally with:
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --features array --open
Not sure how to test end-to-end (as generated by docs.rs) from a PR.
Closes #228
Sample:
=> Enabled docs.rs feature gate flag rendering.

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
=> Added `Rasterband::set_no_data` accepting `Option<f64>`.

CHANGES.md, src/raster/rasterband.rs
Before the private function `map_resample_alg` was the only way to get the expected GDAL enumeration value.
---
Before this change, you had to copy `map_resample_alg` (because it was private) when calling into `gdal-sys` functions needing the resampling algorithm (e.g. `GDALAutoCreateWarpedVRT`). Instead of making `pub fn map_resample_alg ...`, took the approach that more tightly binds the C-side types to the Rust enum. Makes the association more clear, and less error prone in the future.
=> Made mapping between `ResampleAlg` and `GDALRIOResampleAlg` more direct.

CHANGES.md, src/cpl.rs, src/dataset.rs, src/utils.rs
---
New methods:
* `len`
* `is_empty`
New traits: 
* `Debug`
* `Iterator`
New tests:
* `has_length`
* `can_be_empty`
* `invalid_keys`
* `basic_list`
* `debug_fmt`
* `has_iterator`
Also tested under:
ASAN_OPTIONS=detect_stack_use_after_return=1,sanitize-address-use-after-return=always RUSTFLAGS=-Zsanitizer=address cargo +nightly test cpl --target aarch64-apple-darwin
=> Quality-of-life additions to `CplStringList`.

.github/workflows/ci.yml
---
GitHub deprecated the Node 12 runtime, we should probably upgrade.
=> Bump `actions/checkout`

.github/workflows/ci.yml, bors.toml
---
`actions-rs` is unmaintained, and doesn't bring us that much. I think we might lose the nice GitHub integration, but it wasn't really working anyway.
=> Call cargo directly instead of using actions-rs/cargo

.github/workflows/ci.yml
=> Use `rustup` instead of `actions-rs/toolchain`

bors.toml
---
Not sure if this was intentional or not, but it seems like a good idea to wait at least for one of those versions.
And we should probably have a policy for which versions we test on.
=> Wait for `osgeo/gdal` tests to complete

CHANGES.md, src/driver.rs, src/raster/mdarray.rs, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs, src/raster/types.rs
---
Primarily adds `GdalTypeDescriptor` for enabling runtime inspection of `GDALDataType` properties.
**Note, potentially breaking change**: `GDALDataType` is no longer `pub use` in `gdal::raster`, 
as `GdalType` and `GdalTypeDescriptor` sufficiently cover use cases in safe code. 
Still accessible via `gdal_sys::GDALDataType`.
---
=> Filling out `GDALDataType` metadata and utility support.

.cargo/config.toml, Cargo.toml, src/errors.rs, src/vector/feature.rs, src/vector/vector_tests/mod.rs
=> Fix deprecations from chrono 0.4.23.

CHANGES.md, examples/read_write_ogr.rs, examples/read_write_ogr_datetime.rs, src/vector/feature.rs, src/vector/mod.rs, src/vector/vector_tests/mod.rs
- [✓] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [✓] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
I've run into a few instances where I'm loading data uploaded from users (for example CSV files) where GDAL isn't able to find any geometry.  In instances where you might be working with user-provided data with no geometry, calls to `Feature::geometry()` simply panic. 
This PR documents renders `Feature::geometry` non-panicking by returning an `Option<&Geometry>`
=> Handling cases where feature may not have any geometry at all

CHANGES.md, src/vector/layer.rs
=> Changed return type of Layer::spatial_ref from `Result` to `Option`.

CHANGES.md, src/cpl.rs, src/metadata.rs, src/test_utils.rs, src/vector/geometry.rs, src/vector/layer.rs, src/vector/vector_tests/mod.rs, src/vector/vector_tests/sql.rs
---
Partially addresses #306.
cc: @thomas001
=> Implements `Geometry::make_valid`.

CHANGES.md, src/cpl.rs, src/vector/geometry.rs
---
This isn't _that_ ugly, and I think it's better than panicking in a `From` implementation.
=> Replace `CslStringList` `From` implementation with `TryFrom`

CHANGES.md, src/cpl.rs
---
This method wraps gdal_sys::CSLAddString.
This method is useful when constructing argument lists for option structs for the various utility functions found in gdal_utils, such as GDALWarp and GDALTranslate.
=> Add CslStringList::add_string

CHANGES.md, src/spatial_ref/srs.rs, src/vector/geometry.rs, src/vector/layer.rs, src/vector/mod.rs
=> Added `envelope*` methods to `Geometry`.

src/spatial_ref/srs.rs
---
This fixes a small typo in the `transform_bounds` docstring.
=> Fix transform_bounds docstring (min/max confusion)

CHANGES.md, Cargo.toml, build.rs, gdal-sys/Cargo.toml, gdal-sys/build.rs, gdal-sys/src/lib.rs
=> link and version

CHANGES.md, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs
---
I only needed this for the ballpark option, because I found it surprising that it's possible by default to transform between CRSes that are only valid on opposite sides of the world. I didn't change this default though.
The other three options are wrapped, but I don't understand them well enough to add tests for them.
=> Implement CoordTransformOptions and CoordTransform::new_with_options constructor

CHANGES.md, src/vector/geometry.rs
=> Add `Geometry::length`

.gitignore, CHANGES.md, src/spatial_ref/srs.rs, src/spatial_ref/tests.rs
=> Add SpatialRef::to_projjson()

src/driver.rs
=> Pass `GDT_Unknown` for vector layers

src/vector/ops/set.rs
---
Context: https://github.com/georust/gdal/pull/379#discussion_r1135734190
=> Updated `set.rs` docs to be more consistent with those in `predicates.rs`.

Cargo.toml, gdal-sys/Cargo.toml
=> Added to "Geospatial" crates.io category.

.github/workflows/sanitizer.yml
---
If I've configured this correctly, once `sanitizer.yml` is on the `master` branch, we should be able to manually initiate running of this workflow on PRs via the [`workflow_dispatch`](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) trigger.
Notes:
* Makes use of [`cargo-careful`](https://github.com/RalfJung/cargo-careful)
* Among other things, `cargo-careful` enables [`AddressSanitizer`](https://github.com/japaric/rust-san#addresssanitizer), whose options can be configured via `ASAN_OPTIONS`
=> GHA Workflow for running tests under a more strict memory checking environment

CHANGES.md, src/gcp.rs
=> Add GCP access API

src/gcp.rs
=> Document panicking behavior in `Dataset::set_gcps`

.github/workflows/ci.yml, CHANGES.md, bors.toml, src/raster/tests.rs, src/raster/types.rs, src/spatial_ref/srs.rs
=> Add `GDT_Int8`, test GDAL 3.7 on CI and refactor workflow

CHANGES.md, src/gcp.rs, src/raster/rasterband.rs, src/raster/tests.rs, src/spatial_ref/srs.rs
=> Tweak `RasterBand::actual_block_size` API and replace asserts with `try_into`

.github/workflows/ci.yml, CHANGES.md, src/raster/mdarray.rs
---
~~I didn't add it to CI because one of the tests SIGSEGVs for some reason (probably that NetCDF thing)~~
=> Fix build error on GDAL 3.1

.gitignore, src/vector/geometry.rs
---
This impl impl DerefMut trait for GeoemetryRef. This geometry of Geometery::get_geometry(i32) function can modify point coordinate.
=> impl DerefMut trait for GeoemetryRef 

src/vector/geometry.rs, src/vsi.rs
This fixes linting for clippy > 1.71 which introduced a new [default_constructed_unit_structs](https://rust-lang.github.io/rust-clippy/master/index.html#/default_constructed_unit_structs) (see [clippy's changelog](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md))
---
=> Fix linting on clippy > 1.71

CHANGES.md, Cargo.toml
- [x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
=> prepare 0.16.0 changelog + version

CHANGES.md, build.rs, gdal-sys/build.rs
=> Work around GDAL dev version numbering

CHANGES.md, src/raster/mdarray.rs
=> Don't derive Clone, PartialEq and Eq for ExtendedDataType

CHANGES.md, src/raster/rasterband.rs, src/raster/rasterize.rs
=> Make raster index usize

CHANGES.md, src/spatial_ref/srs.rs, src/spatial_ref/transform.rs, src/vector/layer.rs
=> Make SpatialRef::set_axis_mapping_strategy take self by mut

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
=> Added `{Display|FromStr} for ResampleAlg` and `ResampleAlg::iter`.

src/vsi.rs
Fixes leak reported by ``cargo valgrind test --lib``:
```
Error leaked 200 B in 1 block
Info at malloc
at CPLMalloc
at CPLCalloc
at CPLStringList::EnsureAllocation(int)
at CPLStringList::AddStringDirectly(char*)
at unknown
at unknown
at gdal::vsi::_read_dir (vsi.rs:30)
at gdal::vsi::read_dir (vsi.rs:18)
at gdal::vsi::tests::test_vsi_read_dir (vsi.rs:314)
at gdal::vsi::tests::test_vsi_read_dir::{{closure}} (vsi.rs:294)
at core::ops::function::FnOnce::call_once (function.rs:250)
Error leaked 219 B in 1 block
Info at malloc
at CPLMalloc
at CPLCalloc
at CPLStringList::EnsureAllocation(int)
at CPLStringList::AddStringDirectly(char*)
at VSIReadDirRecursive
at gdal::vsi::_read_dir (vsi.rs:24)
at gdal::vsi::read_dir (vsi.rs:18)
at gdal::vsi::tests::test_vsi_read_dir (vsi.rs:325)
at …
```
=> _read_dir(): fix memory leak

src/vector/geometry.rs
=> Stop using deprecated OGR_G_Equal

src/raster/mdarray.rs
---
Alternative to https://github.com/georust/gdal/pull/475.
We move the FFI code into an `unsafe` function that takes a pointer and validate the output length in the caller.
r? @rouault, r? @metasim
=> Validate output length in MDArray::read_into_slice

CHANGES.md, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs
---
This PR exposes 2 GDAL methods to calculate band histograms (default and user-defined).
=> Add histogram calculation for RasterBand

CHANGES.md, src/vector/ops/set.rs
=> Add `Geometry::difference`

CHANGES.md, src/raster/rasterband.rs
=> Check output type in `read_block`

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
=> Add `RasterBand::write_block`

CHANGES.md, gdal-sys/build.rs
---
Defers the `gdal_i.lib` missing message until after the pkg-config check and outputs pkg-config metadata in case of a static build.
=> Fixes for static pkg-config Windows build

CHANGES.md, src/driver.rs, src/errors.rs, src/raster/rasterband.rs, src/vector/layer.rs
---
Scope:
* `Driver::create.*`
* `Rasterband::overview`
* `Dataset::{layer|into_layer|layer_count}`
Closes #495
=> Changed a number of APIs using `isize` when `usize` is semantically more appropriate

CHANGES.md, src/vector/feature.rs
---
Closes #427 
Credit to @nms-scribe
=> Implemented `Feature::set_field_null`

CHANGES.md, src/vector/feature.rs
---
CC https://github.com/georust/gdal/issues/427#issuecomment-1865113102
=> Clean up Feature::set_field_null

CHANGES.md, src/vector/feature.rs
=> Add Feature::unset_field

CHANGES.md, src/driver.rs
---
Fixes #512 
I've done the simplest implementation for the first commit:
```rust
pub struct DriverIterator {
current: usize,
}
impl DriverIterator {
pub fn new() -> Self {
DriverIterator { current: 0 }
}
}
impl Iterator for DriverIterator {
type Item = Driver;
fn next(&mut self) -> Option<Self::Item> {
match DriverManager::get_driver(self.current) {
Ok(d) => {
self.current += 1;
Some(d)
}
Err(_) => None,
}
}
}
```
Which seems too simple, so I'm thinking of adding the ability to filter by metadata.
Which would be something like this:
```rust
pub struct DriverIterator {
current: usize,
filters: Vec<String>,
}
impl DriverIterator {
pub fn all() -> Self {
DriverIterator {
current: 0,
filters: vec![],
}
}
pub fn vectors() -> Self {
DriverIterator {
current: 0,
filters: …
```
=> Add `DriverIterator` to iterate though the registered drivers

Cargo.toml, examples/read_ogr_arrow.rs
=> Use `arrow` instead of `arrow2` in the example

CHANGES.md, src/dataset.rs, src/driver.rs, src/raster/create_options.rs, src/raster/mod.rs, src/raster/rasterband.rs, src/raster/tests.rs
---
This:
```rust
let options = [
RasterCreationOption {
key: "TILED",
value: "YES",
},
RasterCreationOption {
key: "BLOCKXSIZE",
value: "16",
},
RasterCreationOption {
key: "BLOCKYSIZE",
value: "16",
},
];
```
is now this:
```rust
let options = RasterCreationOptions::from_iter([
"TILED=YES", "BLOCKXSIZE=16", "BLOCKYSIZE=16"
]);
```
=> Unified raster creation options over `CplStringList`.

gdal-sys/build.rs
Hi,
The panic that arises when there are no pre-build bindings available is not that explicit and may confuse some users into thinking there's something wrong with GDAL.
Thanks!
---
=> build: no bindings: make error more explicit

CHANGES.md, src/raster/rasterband.rs, src/raster/tests.rs
---
This PR adds safe bindings for https://docs.rs/gdal-sys/latest/gdal_sys/fn.GDALFillRaster.html (https://gdal.org/api/gdalrasterband_cpp.html#classGDALRasterBand_1a55bf20527df638dc48bf25e2ff26f353)
The C++ API has a default value for the `dfImaginaryValue` param which is missing from the C API, so I reintroduced via an `Option`+`.unwrap_or`. Let me know if this isn't acceptable.
I also haven't tested that parameter, as I'm unsure how to read it back.
=> Add `Rasterband::fill`

src/dataset.rs, src/spatial_ref/srs.rs
This otherwise hits an assertion in gdal debug builds for the OSRClone method
---
See https://github.com/OSGeo/gdal/blob/master/ogr/ogrspatialreference.cpp#L1406 for the relevant assertion in gdal
=> Catch potential null pointers returned by `Dataset::spatial_ref`

src/gcp.rs
---
Noticed this when upgrading to latest rust/running tests
```
--- STDOUT:              mio-gdal metadata::test::valid_nitf ---
running 1 test
--- STDERR:              mio-gdal metadata::test::valid_nitf ---
thread 'metadata::test::valid_nitf' panicked at library/core/src/panicking.rs:156:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
0: rust_begin_unwind
at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
1: core::panicking::panic_nounwind_fmt::runtime
at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:110:18
2: core::panicking::panic_nounwind_fmt
at …
```
=> return empty slice when there are no gcps

CHANGES.md, src/vector/defn.rs, src/vector/layer.rs
=> Field: map more methods

gdal-src/Cargo.toml, gdal-src/build.rs, gdal-src/src/lib.rs
---
* Use the `netcdf-sys` crate to automatically link the correct `netcdf-c`
* Use the more updated fork of `hdf5-rust`, as the original crate has not had a release for quite some time https://github.com/aldanor/hdf5-rust/issues/295
=> Use hdf5-metno fork and netcdf-sys

.github/workflows/ci.yml, .typos.toml, gdal-sys/Readme.md, src/geo_transform.rs
=> Add typos to CI

CHANGES.md, Cargo.toml, src/raster/buffer.rs
This PR upgrades the ndarray dependency from 0.15 to 0.16
---
=> upgrade ndarray to 0.16

gdal-src/Cargo.toml
This commit adds an explicit include to the `Cargo.toml` file of gdal-src to minimize the amount of code uploaded to crates.io. This reduces the uncompressed package size from >100MB to ~50MB. This is still larger than what's allowed by crates.io by default, but I know that it is possible to get an exception from these default limits by just asking with a good reason. Source code from an existing established open source project counts as good reason, so that's just something that needs to be done before publishing the first version.
The last time I had this problem the workflow was as follows:
1. Publish an empty version
2. Ask the crates.io team to bump the limit, e.g. via zulip
3. Publish the real code.
---
=> Add an explicit include to gdal-src Cargo.toml

.github/workflows/ci.yml, CHANGES.md, src/vector/layer.rs
---
I noticed this was not present, so I just added a crude implementation. Might be nice to add `delete_layer_by_name` option as well.
If there are more unimplemented methods, we can add as well.
=> Add delete layer method and tests in doc

CHANGES.md, examples/read_write_ogr.rs, examples/read_write_ogr_datetime.rs, examples/write_ogr.rs, src/vector/defn.rs, src/vector/feature.rs, src/vector/layer.rs, src/vector/sql.rs
---
Field access by name tends to be very slow (I've seen it take 30% of the time in some programs), but beginners are unlikely to realize that they're doing a number of expensive lookups per feature.
Summary of changes:
- drop field getters that take a field name
- change the field setters to take an index instead of a name (the index versions were missing)
- make `field_count` return `usize` for consistency
- add `Defn::field_index` and make `Feature::field_index` public
- drop `LayerAccess::create_feature_fields` (it could be updated, but it's a bit weird)
=> Take the field index, not name, in the feature getters and setters

.github/workflows/ci.yml
=> Disable Valgrind because of leak in 1.83 unit test runner

CHANGES.md, src/dataset.rs, src/vector/layer.rs
---
This is for doing things like `Dataset::has_capability(DatasetCaps::ODsCTransactions)` to check if dataset supports Transaction. 
I added the Capabilities from:
- https://gdal.org/en/latest/doxygen/ogr__api_8h.html#a9010219bbc2e32627064ed860048d979
- https://gdal.org/en/latest/doxygen/gdal_8h.html#a8dc635a536f123e1b03004dc74b4da86
I followed the example of `Layer::has_capability` for both of them.
This will help use the `if {} else {}` block for capability based logic like the one mentioned in #582 
Basically it'll make it so that @lnicola 's Suggestion given below can work:
```rust
let stuffs = |d: &Dataset| -> Result<()> { ... };
if /* transactions are supported */ {
let txn = d.start_transaction()?;
stuffs(&txn)?;
txn.commit()?;
} else {
stuffs(&d)?;
}
```
Currently, without this …
=> Add `Dataset::has_capability`

CHANGES.md, src/config.rs, src/cpl.rs, src/dataset.rs, src/driver.rs, src/gcp.rs, src/lib.rs, src/metadata.rs, src/raster/mdarray.rs, src/raster/rasterband.rs, src/raster/types.rs, src/spatial_ref/srs.rs, src/utils.rs, src/vector/defn.rs, src/vector/feature.rs, src/vector/geometry.rs, src/vector/layer.rs, src/vector/ops/conversions/formats.rs, src/version.rs
---
Closes #588
This makes `_string` and `_pathbuf` fallible and updates the callers to some sensible defaults (by returning empty strings in many places, which seems similar in spirit to what GDAL does). There's an API change on `SpatialRef::authority_name` and some friends, which used to return `Result`, but where `Option` feels more appropriate for what they're doing. It might be a little annoying for the users, though.
=> Make string conversion fallible

gdal-src/Cargo.toml
---
Now that there is a `proj-sys` release that supports these newer versions we can support them in gdal-src as well.
=> Allow newer libsqlite3-sys versions

CHANGES.md, src/vector/geometry.rs, src/vector/layer.rs, src/vector/mod.rs, src/vector/ops/conversions/formats.rs, src/vector/ops/conversions/gdal_to_geo.rs
---
This PR seeks to add bindings for GDAL functions relating to higher-dimension geometry, in particular Measured geometry, with some other minor fixes/additions.
Added methods for `Geometry`:
- `add_point_zm`
- `add_point_m`
- `set_point_zm`
- `set_point_m`
- `get_point_zm`
- `get_point_vec_zm`
- `iso_wkt`
- `iso_wkb`
Considering renaming `get_point_vec_zm` to `get_point_zm_vec`, though neither exactly roll off the tongue.
Also modified the Debug impl. for `Geometry` to use iso_wkt in cases of measured geometry.
=> Add M-dim bindings

CHANGES.md, src/vector/geometry.rs, src/vector/layer.rs, src/vector/mod.rs, src/vector/ops/conversions/formats.rs, src/vector/ops/conversions/gdal_to_geo.rs
=> Unsquish after #600

gdal-src/Cargo.toml
=> Bump bundled GDAL to 3.10.1

.github/workflows/ci.yml, CHANGES.md, Cargo.lock, gdal-src/Cargo.toml
Previous PR #616 reverted the version back from 3.10.2 to 3.9.1
---
=> Bump referenced gdal version to 3.10.3

src/lib.rs
---
Sorry for not noticing this, I think I added this feature (?), but the struct is not accessible publicly. This fixes it
https://docs.rs/gdal/latest/gdal/struct.Dataset.html#method.has_capability
=> Make DatasetCapability accessible
